language: android
jdk: oraclejdk8
before_install:
  - nvm install 6
  - node --version
install:
  - cd test && cd ExampleApp && npm install
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16
script:
  - ./gradlew assembleRelease
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
      bash scripts/release.sh;
      bash scripts/publish-docs.sh;
    fi
